<a href="https://colab.research.google.com/github/DL-POWER/Deep-Learning/blob/master/projects/Question_and_Answer_Kaggle_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [0]:
import csv

In [0]:
num_sentences = 0
questions = []
answers = []
labels = []
with open("/content/drive/My Drive/train.csv") as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    next(reader)
    for row in reader:
        questions.append(row[2]);
        answers.append(row[5])
        labels.append(row[11:])
        num_sentences = num_sentences + 1

In [6]:
len(questions)

6079

In [7]:
new_questions=  []
for string1 in questions:
  s = ""
  for e in string1:
    if(e.isalnum()):
      s+=e
    elif(e==' '):
      s+=e
    elif(e=='.'):
      s+=' '
  new_questions.append(s)
print(s)

Newbie question Why is it that theres a bazillion different types of screws Why cant we just always use one standard screw type Are there advantagesdisadvantages to the different types Are there times when one type is preferred over anotherHelp me understand why there isnt one screw to rule them all 


In [8]:
new_answers =  []
for string1 in answers:
  s = ""
  for e in string1:
    if(e.isalnum()):
      s+=e
    elif(e==' '):
      s+=e
    elif(e=='.'):
      s+=' '
  new_answers.append(s)
print(s)

First I really like Erics answer for practical reasons   But there is another side to screw head diversity  Security In the end its usually a temporary measure   Once a company invents a new screw some third party will start selling tools to remove them   But for a time any new screw design means the only people who can open your parts are certified workshops youve given tools to   Personally I see this a lot in electronic equipment where the original manufacturer wants some aspect of design kept private or doesnt want aftermarket mods made to things they sell   Nintendo is particularly active in inventing new screws Examples of security screws include 3prong Torx variants and Allen heads with a raised dot in the middle of the screw head to stop standard Allen wrenches from fitting If youd like to see a much more industrial version find a car which has been booted and look at the bolt   Ive seen circular bolt heads with an offcenter circular hollow inside   No shoulders or slots to gra

In [9]:
maxx  = 0
total = 0
for sentence in new_answers:
  total = total+len(sentence.split())
  if(len(sentence.split())>maxx):
    maxx = len(sentence.split())
    print(len(sentence.split()))
    

print(maxx)
print(total/6079)

150
183
246
704
755
994
1133
1237
2373
2373
129.7215002467511


In [10]:
len(new_questions)

6079

In [11]:
string1 = "hello,! how u doing"
s = ""
for e in string1:
  if(e.isalnum()):
    s+=e
  elif(e==' '):
    s+=e
print(s)

hello how u doing


In [12]:
total_sentences = []
for question in new_questions:
  total_sentences.append(question)
for answer in new_answers:
  total_sentences.append(answer)
len(total_sentences)

12158

In [0]:
embedding_dim = 100
max_length = 150
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"

In [0]:
tokenizer = Tokenizer(oov_token=oov_tok)
tokenizer.fit_on_texts(total_sentences)

word_index = tokenizer.word_index
vocab_size=len(word_index)

In [31]:
print(vocab_size)

87436


In [0]:
question_sequences = tokenizer.texts_to_sequences(new_questions)
question_padded = pad_sequences(question_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

answer_sequences = tokenizer.texts_to_sequences(new_answers)
answer_padded = pad_sequences(answer_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)


In [33]:
len(question_sequences)

6079

In [34]:
print(len(answer_sequences[1]))
print(answer_sequences[1])
print(answer_padded[1])

74
[11, 137, 15, 1366, 3, 181, 87, 2, 903, 8, 2931, 54011, 19069, 2931, 2739, 28, 596, 24417, 17, 23204, 1264, 17264, 5502, 5839, 1665, 1131, 89, 4, 14141, 57, 29, 156, 2366, 5124, 11, 188, 4, 1173, 1834, 10, 10176, 35, 37595, 2, 14140, 17, 2931, 2931, 27, 2, 261, 6520, 2339, 35, 5904, 87, 2, 6130, 5648, 4, 972, 1130, 17, 261, 54012, 9058, 4544, 11, 37596, 823, 18, 20, 121, 2931]
[   11   137    15  1366     3   181    87     2   903     8  2931 54011
 19069  2931  2739    28   596 24417    17 23204  1264 17264  5502  5839
  1665  1131    89     4 14141    57    29   156  2366  5124    11   188
     4  1173  1834    10 10176    35 37595     2 14140    17  2931  2931
    27     2   261  6520  2339    35  5904    87     2  6130  5648     4
   972  1130    17   261 54012  9058  4544    11 37596   823    18    20
   121  2931     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0   

In [35]:
final_x[1]

array([    5,    64,   179,     3,   273,    37,  2374,     8,  1188,
           2,  2931,   279,    16,   280,  5948,  1530,     3,     9,
           2,  5949,  2130,   377,   416,    13, 20101,   384,   280,
         771,     4, 11120,     6,     4, 14140,     4, 14140,     6,
           4, 16190,   988,   537,    13, 14141,   384,   374,     4,
       14141,     6,     4,   106,   444, 16190,   596,   583,    39,
          10,     6,    28, 11121,     8,    92,    25,    55,  5468,
           4,  1130,  9275,     7, 11120,  9275,    35,  1719,     3,
          18,   324, 11122,    23,    13,    46,   332,     2, 11120,
          38,  1516, 20102,    57,     4,   686,  2931,  2739,  1131,
        3355,   280,  5948,  2062,   116,   115,     8,     4,  9275,
          20,   158,    55,  6520,     7,  6210,   123,   207,  1317,
       11123,     7,  3650,  5950,    82,     4,  3098, 11124,   123,
         207,    28, 14142, 16191,     2,  1131,  6836,    83,    77,
         115,    10,

In [0]:
question_padded_np_array = np.array(question_padded)
answer_padded_np_array = np.array(answer_padded)



In [0]:
a = np.array(([[1,2,3],[4,5,6]]))
b = np.array([[7,8,9],[3,4,5]])

In [43]:
print(word_index['i'])
print(word_index.get('i'))

5
5


In [39]:
c = np.append(a,b,axis = 1)
print(c)

[[1 2 3 7 8 9]
 [4 5 6 3 4 5]]


In [40]:
final_x = np.append(question_padded_np_array,answer_padded_np_array,axis = 1)
print(final_x.shape)

(6079, 300)


In [49]:
!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/glove.6B.100d.txt \
    -O /tmp/glove.6B.100d.txt
embeddings_index = {};
with open('/tmp/glove.6B.100d.txt') as f:
    for line in f:
        values = line.split();
        word = values[0];
        coefs = np.asarray(values[1:], dtype='float32');
        embeddings_index[word] = coefs;

embeddings_matrix = np.zeros((vocab_size+1, embedding_dim));
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word);
    if embedding_vector is not None:
        embeddings_matrix[i] = embedding_vector;

--2019-12-17 05:41:27--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/glove.6B.100d.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.195.128, 2607:f8b0:400e:c08::80
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.195.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 347116733 (331M) [text/plain]
Saving to: ‘/tmp/glove.6B.100d.txt’

/tmp/glove.6B.100d. 100%[===================>] 331.04M   198MB/s    in 1.7s    

2019-12-17 05:41:29 (198 MB/s) - ‘/tmp/glove.6B.100d.txt’ saved [347116733/347116733]



In [54]:
embeddings_matrix[2]

array([-0.038194  , -0.24487001,  0.72812003, -0.39961001,  0.083172  ,
        0.043953  , -0.39140999,  0.3344    , -0.57545   ,  0.087459  ,
        0.28786999, -0.06731   ,  0.30906001, -0.26383999, -0.13231   ,
       -0.20757   ,  0.33395001, -0.33848   , -0.31742999, -0.48335999,
        0.1464    , -0.37303999,  0.34577   ,  0.052041  ,  0.44946   ,
       -0.46970999,  0.02628   , -0.54154998, -0.15518001, -0.14106999,
       -0.039722  ,  0.28277001,  0.14393   ,  0.23464   , -0.31020999,
        0.086173  ,  0.20397   ,  0.52623999,  0.17163999, -0.082378  ,
       -0.71787   , -0.41531   ,  0.20334999, -0.12763   ,  0.41367   ,
        0.55186999,  0.57907999, -0.33476999, -0.36559001, -0.54856998,
       -0.062892  ,  0.26583999,  0.30204999,  0.99774998, -0.80480999,
       -3.0243001 ,  0.01254   , -0.36941999,  2.21670008,  0.72201002,
       -0.24978   ,  0.92136002,  0.034514  ,  0.46744999,  1.10790002,
       -0.19358   , -0.074575  ,  0.23353   , -0.052062  , -0.22

In [47]:
print((embeddings_matrix).shape)

(87436, 100)


In [77]:
labels = np.array(labels)
print(labels.shape)

(6079, 30)


In [83]:
labels[:,0]

array(['1.0', '1.0', '0.8888888888888888', ..., '0.8888888888888888',
       '1.0', '1.0'], dtype='<U19')

In [85]:
print(final_x.shape)
print(y1.shape)

(6079, 300)
(6079,)


In [0]:
y1  = labels[:,0]

In [86]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size+1, embedding_dim, input_length=2*max_length, weights=[embeddings_matrix], trainable=None),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.LSTM(64,return_sequences = True),
    #tf.keras.layers.LSTM(64,activation='relu',return_sequences=True),
    tf.keras.layers.MaxPooling1D(pool_size=4),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(1, activation="softmax")
])
model.compile(loss='mean_absolute_error',optimizer='adam',metrics=['accuracy'])
model.summary()

num_epochs = 50
history = model.fit(final_x, y1, epochs=10,verbose=1)

print("Training Complete")

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 300, 100)          8743700   
_________________________________________________________________
lstm_14 (LSTM)               (None, 300, 64)           42240     
_________________________________________________________________
max_pooling1d_7 (MaxPooling1 (None, 75, 64)            0         
_________________________________________________________________
lstm_15 (LSTM)               (None, 64)                33024     
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 65        
Total params: 8,819,029
Trainable params: 75,329
Non-trainable params: 8,743,700
_________________________________________________________________
Train on 6079 samples
Epoch 1/10
6079/6079 [==============================] - 93s 15ms/sample - loss: 0.1

In [0]:
test_model = tf.keras.Sequential([tf.keras.layers.Embedding(vocab_size+1, embedding_dim, input_length=1, weights=[embeddings_matrix], trainable=None)])

In [58]:
test_model.predict([5])

array([[[-0.046539 ,  0.61966  ,  0.56647  , -0.46584  , -1.189    ,
          0.44599  ,  0.066035 ,  0.3191   ,  0.14679  , -0.22119  ,
          0.79239  ,  0.29905  ,  0.16073  ,  0.025324 ,  0.18678  ,
         -0.31001  , -0.28108  ,  0.60515  , -1.0654   ,  0.52476  ,
          0.064152 ,  1.0358   , -0.40779  , -0.38011  ,  0.30801  ,
          0.59964  , -0.26991  , -0.76035  ,  0.94222  , -0.46919  ,
         -0.18278  ,  0.90652  ,  0.79671  ,  0.24825  ,  0.25713  ,
          0.6232   , -0.44768  ,  0.65357  ,  0.76902  , -0.51229  ,
         -0.44333  , -0.21867  ,  0.3837   , -1.1483   , -0.94398  ,
         -0.15062  ,  0.30012  , -0.57806  ,  0.20175  , -1.6591   ,
         -0.079195 ,  0.026423 ,  0.22051  ,  0.99714  , -0.57539  ,
         -2.7266   ,  0.31448  ,  0.70522  ,  1.4381   ,  0.99126  ,
          0.13976  ,  1.3474   , -1.1753   ,  0.0039503,  1.0298   ,
          0.064637 ,  0.90887  ,  0.82872  , -0.47003  , -0.10575  ,
          0.5916   , -0.4221   ,  

In [59]:
embeddings_matrix[5]

array([-0.046539  ,  0.61966002,  0.56647003, -0.46584001, -1.18900001,
        0.44599   ,  0.066035  ,  0.31909999,  0.14679   , -0.22119001,
        0.79238999,  0.29905   ,  0.16073   ,  0.025324  ,  0.18678001,
       -0.31000999, -0.28108001,  0.60514998, -1.0654    ,  0.52476001,
        0.064152  ,  1.03579998, -0.40779001, -0.38011   ,  0.30801001,
        0.59964001, -0.26991001, -0.76034999,  0.94221997, -0.46919   ,
       -0.18278   ,  0.90652001,  0.79671001,  0.24824999,  0.25713   ,
        0.6232    , -0.44768   ,  0.65357   ,  0.76902002, -0.51229   ,
       -0.44332999, -0.21867   ,  0.38370001, -1.14830005, -0.94397998,
       -0.15062   ,  0.30012   , -0.57805997,  0.20175   , -1.65910006,
       -0.079195  ,  0.026423  ,  0.22051001,  0.99713999, -0.57538998,
       -2.72659993,  0.31448001,  0.70521998,  1.43809998,  0.99125999,
        0.13976   ,  1.34739995, -1.1753    ,  0.0039503 ,  1.02980006,
        0.064637  ,  0.90886998,  0.82871997, -0.47003001, -0.10